# Loads default set of integrations. Do not remove.
default_config:

frontend:
  themes: !include themes.yaml

tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

conversation:

binary_sensor:
  - platform: ping
    host: pajew.ski
